_base_: [
    './train.yaml',
    '../_base_/data/cls_data.py',
    '../_base_/models/classifiers/classifier.py',
]

runner:
    max_epochs: 20

optimizer_config:
    _delete_: True
    grad_clip:
        max_norm: 5
        norm_type: 2

optimizer:
    type: SGD
    lr: 0.01
    momentum: 0.9
    weight_decay: 0.0005

evaluation: 
    metric: ['accuracy', 'class_accuracy']

task_adapt: 
    type: 'mpa'
    op: 'REPLACE'

custom_hooks:
- type: NoBiasDecayHook

